### ISSUE TITLE
Undefined method `taggings_count`

### ISSUE THREAD

**Issue by stephenyeargin** [marius-balteanu/redmine_tags#14]
````
 Completed 500 Internal Server Error in 314ms (ActiveRecord: 9.1ms)
 
 ActionView::Template::Error (undefined method `taggings_count' for #<ActsAsTaggableOn::Tag id: 
     2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
     3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
     4:   <h3><%= l :tags %></h3>
     5:   <%= render_sidebar_tags %>
     6: <% end %>
   lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
   lib/redmine/hook.rb:117:in `map'
   lib/redmine/hook.rb:117:in `block in render_on'
   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
   lib/redmine/hook.rb:61:in `each'
   lib/redmine/hook.rb:61:in `block in call_hook'
   lib/redmine/hook.rb:58:in `tap'
   lib/redmine/hook.rb:58:in `call_hook'
   lib/redmine/hook.rb:167:in `call_hook'
   app/views/issues/_sidebar.html.erb:18:in `_app_views_issues__sidebar_html_erb__31403687789409
   app/views/issues/index.html.erb:99:in `block in _app_views_issues_index_html_erb__35659663295
   app/views/issues/index.html.erb:98:in `_app_views_issues_index_html_erb__3565966329506215711_
   app/controllers/issues_controller.rb:77:in `block (2 levels) in index'
   app/controllers/issues_controller.rb:76:in `index'
   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by stephenyeargin** [comment]
Duplicate of #13 (must have hit submit too many times)
